# Based on https://gitlab.fi.muni.cz/unix/examples/ci-examples/-/blob/java-maven/.gitlab-ci.yml
image: maven:3-jdk-11

build:
  tags:
    - shared-fi
  script:
    - mvn -v
    - mvn --no-transfer-progress clean
    - mvn -ntp verify
